import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import {parseHTML} from 'linkedom';

const html=readFileSync(new URL('../../x_engine/dashboard.html',import.meta.url),'utf8');
const {document}=parseHTML(html);
const runtime=vm.createContext({URL,document});
vm.runInContext(html.split('<script>')[1].split('async function loadFeed')[0],runtime);
const run=code=>vm.runInContext(code,runtime);
const photo={type:'photo',url:'https://pbs.twimg.com/media/example.jpg',alt:'A photo <safe>'};
const video={type:'video',url:'https://video.twimg.com/example.mp4',poster:photo.url};
const item={key:'p:target:1',kind:'quote',target:'target',timestamp:1,text:'My video',url:'https://x.com/i/status/1',
  context:JSON.stringify({media:[video],original:{id:'2',text:'Photos',media:[photo,photo,photo,photo]}})};
run(`state.items=[${JSON.stringify(item)}];render()`);
const feed=document.getElementById('feed');
assert.equal(feed.querySelectorAll('.media-image img').length,4);
assert.equal(feed.querySelectorAll('video').length,1);
assert.equal(feed.querySelector('.media-image img').alt,'A photo <safe>');
assert.ok(feed.querySelector('.media-count-4'));
assert.equal(feed.querySelector('video').closest('a'),null,'Playback controls must not be inside a link');
const player=feed.querySelector('video');
player.currentTime=17;
assert.ok(player.hasAttribute('controls'));
assert.ok(player.hasAttribute('playsinline'));
assert.ok(!player.hasAttribute('autoplay'));
assert.equal(player.getAttribute('preload'),'none');
run('render()');
assert.equal(feed.querySelector('video'),player,'Unchanged polling must preserve the player');
run("state.items[0].likes=42;state.items[0].text='Updated caption';render()");
assert.equal(feed.querySelector('video'),player,'Metric and text updates must preserve the player');
assert.equal(player.currentTime,17);
assert.equal(feed.querySelector('.body').textContent,'Updated caption');
run(`state.items.unshift(${JSON.stringify({...item,key:'p:target:3',context:'{}'})});render()`);
assert.equal(feed.querySelector('video'),player,'New cards must preserve an existing player');
assert.ok(run(`mediaGallery(${JSON.stringify([{...video,type:'gif'}])})`).includes('loop muted'));
assert.ok(run(`mediaGallery(${JSON.stringify([{...video,url:''}])})`).includes('Playback unavailable'));
assert.equal(run(`mediaGallery(${JSON.stringify([{type:'photo',url:'javascript:alert(1)'},{type:'video',url:'https://evil.test/x.mp4'}])})`),'');
run('state.items=[];render()');
assert.equal(feed.querySelector('video'),null);
console.log('Inline media, safe markup, galleries, and playback preservation passed');
