import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';

const html=readFileSync(new URL('../../x_engine/dashboard.html',import.meta.url),'utf8');
const elements=new Map();
const runtime=vm.createContext({URL,document:{getElementById(id){return elements.get(id)}}});
vm.runInContext(html.split('<script>')[1].split('function render()')[0],runtime);
const run=code=>vm.runInContext(code,runtime);
const item={kind:'follow',target:'watcher',timestamp:1,context:JSON.stringify({id:'42',name:'Project <script>',username:'project'}),smart_accounts:{count:2,state:'complete'}};
const card=run(`card(${JSON.stringify(item)})`);
assert.ok(card.includes('2 SA</button>'));
assert.ok(card.includes('Project &lt;script&gt;'));
assert.ok(!card.includes('<a class="followrow"'),'Badge must not be nested inside a link');
assert.ok(run(`smartBadge({id:'42'}, {count:0,state:'pending'})`).includes('SA …'));
assert.ok(run(`smartBadge({id:'42'}, {count:0,state:'complete'})`).includes('0 SA'));
assert.ok(run(`smartBadge({id:'42'}, {count:2,state:'checking'})`).includes('2+ SA'));
const dialog={dataset:{},open:false,showModal(){this.open=true}};
elements.set('sa-dialog',dialog);
for(const id of ['sa-title','sa-note','sa-list'])elements.set(id,{});
runtime.fetch=async url=>{assert.equal(url,'/api/smart-accounts?id=42');return {ok:true,json:async()=>({state:'complete',count:1,accounts:[{username:'alice',name:'Alice <script>'}]})}};
run(`openSmartAccounts({dataset:{saId:'42',saName:'Project'}})`);
await run('loadSmartAccounts()');
assert.ok(dialog.open);
assert.equal(elements.get('sa-title').textContent,'SA following Project');
assert.ok(elements.get('sa-list').innerHTML.includes('https://x.com/alice'));
assert.ok(elements.get('sa-list').innerHTML.includes('Alice &lt;script&gt;'));
assert.ok(elements.get('sa-note').textContent.includes('1 SA followers found.'));
runtime.fetch=async()=>({ok:false});
await run('loadSmartAccounts()');
assert.ok(elements.get('sa-note').textContent.includes('Could not load'));
run(`renderCards=()=>{};state.items=[${JSON.stringify(item)}];syncSmartResult({subject_id:'42',count:6,state:'checking',accounts:[]})`);
assert.equal(run('state.items[0].smart_accounts.count'),6,'Opening a list refreshes the badge on retained older cards');
assert.ok(!run("'accounts' in state.items[0].smart_accounts"));
console.log('SA badges, partial and zero counts, modal loading, escaping, links, and errors passed');
